config:
  # This is a test server run by team Artillery
  # It's designed to be highly scalable
  target: "{{ $env.API_URL }}"
  phases:
    - duration: 600
      # arrivalCount: 10
      #2 requests per second for 10 minutes
      arrivalRate: 2
      name: Sustained peak load
  processor: "./items-payload-generator.js"
  plugins:
    publish-metrics:
      - type: cloudwatch
        region: us-west-2
        namespace: artillery-ecs-farget-network-actions-load
        dimensions:
          - name: Service
            value: items-svc

scenarios:
  - flow:
      - function: "generatePayloadData"
      - post:
          url: "/api/items"
          afterResponse: "printStatus"
          json:
            name: "{{ name }}"
            description: "{{ description }}"
            category: "{{ category }}"
            price: "{{ price }}"
      - think: 2